#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <SOIL/SOIL.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>
#include "glm.h"
